[package]
name = "ratex_nif"
version = "0.1.0"
edition = "2021"

[lib]
name = "ratex_nif"
path = "src/lib.rs"
crate-type = ["cdylib"]

[features]
nif_version_2_15 = ["rustler/nif_version_2_15"]
nif_version_2_16 = ["rustler/nif_version_2_16"]

[dependencies]
rustler = "0.37"
ratex-types  = "0.1.4"
ratex-parser = "0.1.4"
ratex-layout = "0.1.4"
ratex-render = { version = "0.1.4", features = ["embed-fonts"] }
ratex-svg    = { version = "0.1.4", features = ["embed-fonts", "standalone"] }
